name: Github Actions Demo

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

env:
  MY_HOST: "127.0.0.1"
  COMPANY_NAME: "OTL"

jobs:
  build-job:
    runs-on: ubuntu-latest
    env:
      FULLNAME: 'Solar Flare'
    steps:
      - run: echo ${{ vars.COMPANY_NAME }}
      - run: echo ${{ env.COMPANY_NAME }}
      - run: echo ${{ secrets.DB_PASSWORD }}
      - run: echo "My host is $MY_HOST and $FULLNAME"
      - run: echo "Hello ${{ github.actor }}"

  test-job:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - run: echo "Repo is ${{ github.repository }} ${{ env.MY_HOST }}"
      
  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - run: echo "deploy job to production server ${{ job.status }}"